## Feature Extraction Parameter
lidar_topic: /os_cloud_node/points
N_SCAN: 128
Horizon_SCAN: 1024
edge_threshold: 1.0
surf_threshold: 0.1
odometry_surface_leaf_size: 0.4
undistort_scan_before_extraction: true
min_distance: 1.0
max_distance: 55.0

## Bag Param
#bag_path: /home/data/newer_college/2021-04-07-13-49-03-math-easy.bag
#bag_path: /home/data/newer_college/2021-04-07-13-55-18-math-medium.bag
#bag_path: /home/data/newer_college/2021-04-07-13-58-54-math-hard.bag
#bag_path: /home/data/newer_college/2021-04-12-11-06-47-underground-mine-easy.bag
#bag_path: /home/data/newer_college/2021-04-12-11-11-33-underground-mine-medium.bag
#bag_path: /home/data/newer_college/2021-04-12-11-24-30-underground-mine-hard.bag
#bag_path: /home/data/newer_college/2021-07-01-10-37-38-quad-easy.bag
#bag_path: /home/data/newer_college/2021-07-01-10-40-50_0-stairs.bag
#bag_path: /home/data/newer_college/2021-07-01-11-31-35-quad-medium.bag
#bag_path: /home/data/newer_college/2021-07-01-11-35-14-quad-hard.bag
#bag_path: /home/data/newer_college/2021-11-30-17-09-49-park.bag
bag_path: /home/data/newer_college/2021-12-02-10-15-59-cloister.bag

imu_topic: /alphasense_driver_ros/imu
gps_topic: /gps/fix
bag_start: 0
bag_durr: -1

## Methods of data fusion
use_corner_feature: false #true
use_imu_orientation: false

## Spline Param
#knot_distance: 0.1
knot_distance: 0.05

# lidar odometry
keyframe_search_radius: 30.0
keyframe_density: 2.0
corner_leaf_size: 0.2
surface_leaf_size: 0.6
keyframe_adding_angle_threshold: 30
keyframe_adding_dist_meter: 1.0 # 0.5
edge_min_valid_num: 10
surf_min_valid_num: 100
downsample_num: 4 # lidar Correspondence

## ImuStateEstimator
accel_excite_threshold: 0.5
gyro_excite_threshold: 0.5 # not used
sample_num: 5

# For CalibParamManager
# optimization
gyro_weight: 40.0
accel_weight: 1.0
vel_weight: 1
bias_weight: 1
lidar_weight: 20.0

time_offset: 0
extrinsic:
 Trans: [-0.037, -0.008, -0.026]
 Rot: [1.0, 0.0, 0.0,
       0.0,-1.0, 0.0,
       0.0, 0.0,-1.0]

# Loop Closure
loop_closure_enable_flag: false
loop_closure_icp_recognition_manual_check: false
loop_closure_frequency: 1.0
loop_closure_use_full_cloud: true
history_key_frame_search_radius: 40.0
history_key_frame_time_diff: 15.0
history_key_frame_index_diff: 25
history_key_frame_search_num: 25
history_key_frame_fitness_score: 0.5
loop_closure_downsample_leaf_size: 0.2
neighbor_edg_sample_time: 0.1

loop_closure_weights:
    pose_graph_edge_pos_weight: 10.0
    pose_graph_edge_rot_weight: 20.0
    velocity_weight: 1.0
    gyro_weight: 2.0

save_map: true

